service: debitauthorizer
provider:
  name: openwhisk
  runtime: java
  memory: 128
  timeout: 10
package:
  artifact: target/debitauthorizer.jar
functions:
  findBalance:
    handler: target/debitauthorizer.jar:br.com.evandropires.debitauthorizer.function.FindBalanceFunction
    name: debitauthorizer/findBalance
  findCreditCard:
    handler: target/debitauthorizer.jar:br.com.evandropires.debitauthorizer.function.FindCreditCardFunction
    name: debitauthorizer/findCreditCard
  provisionalDebit:
    handler: target/debitauthorizer.jar:br.com.evandropires.debitauthorizer.function.ProvisionalDebitAddFunction
    name: debitauthorizer/provisionalDebit
  provisionalDebitRegister:
    handler: target/debitauthorizer.jar:br.com.evandropires.debitauthorizer.function.ProvisionalDebitRegisterFunction
    name: debitauthorizer/provisionalDebitRegister
  transactionAdd:
    handler: target/debitauthorizer.jar:br.com.evandropires.debitauthorizer.function.TransactionAddFunction
    name: debitauthorizer/transactionAdd
plugins:
  - "serverless-openwhisk"
